Amazon Linux 2023 support
nginxinc/ansible-role-nginx pull request #597
Opened 2023-03-26 18:33 UTC by sbezugliy

### Proposed changes

`Amazon Linux 2023` is not supported by current Ansible role. Also it has some significant differences with `Amazon Linux 1, 2`, so same actions aren't compatible. List of differences and issues:
  - `Fedora` based. (Not sure about full support of Fedora repositories)
  - Doesn't support some packages from `CentOS`, `RHEL` and other mainline distributive repositories, have unsolvable dependencies graphs.
  - Doesn't support `EPEL` repository. `EPEL` is not recommended by creators of distributive.
  - `Dnf` is default package manager. No yum installed.
  - `Python 3` is used by default. `Yum` not supported and require some additional dependencies for Python or installing `python ~= 2.7`.
    Mismatch of versions between `Amazon Linux 2023 Repository` and official `Nginx repository` for Amazon Linux 2023. Added both Nginx repositories: `stable` and `mainline`. Mismatch in versioning convention for Nginx: amazon linux repository uses `nginx-1:<major_version>.<minor_version>`, when Nginx official repository uses `nginx:<major_version>.<minor_version>`. So, as example: `nginx-1:1.20.4` is recognized as higher version then `nginx:1.23.1`. The same with module packages.

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [`CONTRIBUTING`](https://github.com/nginxinc/ansible-role-nginx/blob/main/CONTRIBUTING.md) document
- [x] I have added Molecule tests that prove my fix is effective or that my feature works
- [x] I have checked that any relevant Molecule tests pass after adding my changes
- [x] I have updated any relevant documentation ([`defaults/main/*.yml`](https://github.com/nginxinc/ansible-role-nginx/blob/main/defaults/main/), [`README.md`](https://github.com/nginxinc/ansible-role-nginx/blob/main/README.md) and [`CHANGELOG.md`](https://github.com/nginxinc/ansible-role-nginx/blob/main/CHANGELOG.md))

2023-03-28 18:28 UTC, alessfg commented
Thanks for the PR! I'll get to it asap!

Two initial thoughts before I actually do a review:

a) Looks like you ran `ansible-lint --write`? I might ask you to revert some of the changes the tool does by default. The changes it does are sometimes not that great for readibility
b) Looks like some tests are failing? I had a quick look and all Molecule distro specs are identical across all scenarios, so I am not entirely sure why it sometimes fails? A simple rerun might be good enough to fix those errors, but if they keep failing we might need to look into it a bit more.

2023-03-29 15:22 UTC, jskelly84 approved these changes

2023-03-29 18:40 UTC, alessfg commented
Ok some of these tests are now failing because a new version of NGINX got released over night and it broke some of the Molecule verification tests. I'll open a PR with a fix for that either later today or tomorrow and then we can try to run these tests again :)

2023-04-10 11:39 UTC, alessfg requested changes
Thanks for the PR! It's a good first pass, but we need to:
* Revert all the Ansible Lint formatting changes (the auto formatting capabilities are very much a WIP)
* Add some missing Molecule tests (and figure out why the ones that are here are failing?)
* Remove your usage of `vars` blocks throughout multiple tasks. It adds extra code when a simple double conditional should be enough (and would follow the same format used throughout the rest of the role).
* Double check some `dnf` installation tasks (I made some comments where relevant).

P.S.: I started writing out long/detailed comments but at some stage started making smaller one word comments. LMK if you have any questions 😄

2023-04-10 11:39 UTC, alessfg commented on defaults/main/amplify.yml
> +nginx_amplify_api_key:
Needs to be changed back to null (for clarity)

2023-04-10 11:39 UTC, alessfg commented on meta/main.yml
> +      versions: ["7", "8", "9"]
Can you change double quotes here back to single quotes (I use single quotes for array values)? (Same for the other array/list values in the metadata.)

2023-04-10 11:39 UTC, alessfg commented on molecule/source/molecule.yml
Amazon Linux 2023 tests are missing from the default/distribution/downgrade/downgrade-plus/plus Molecule scenarios :)

2023-04-10 11:39 UTC, alessfg commented on molecule/version/converge.yml
> +          }}.ngx
This needs to go back to how it was before. A single line is much preferable to what it looks like now.

2023-04-10 11:39 UTC, alessfg commented on tasks/amplify/setup-debian.yml
> +    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] https://packages.amplify.nginx.com/py3/{{ ansible_facts['distribution'] | lower
Needs to go back to a single line :)

2023-04-10 11:39 UTC, alessfg commented on tasks/amplify/setup-redhat.yml
> +      == 'Amazon') | ternary('amzn', 'centos') }}/$releasever/$basearch/
Needs to go back to a single line :)

2023-04-10 11:39 UTC, alessfg commented on tasks/config/setup-logrotate.yml
> +  vars:
I am not entirely sure we need this vars block? We can check whether it's Amazon Linux 2023 in the `when` block directly.

2023-04-10 11:39 UTC, alessfg commented on tasks/config/setup-logrotate.yml
> +  vars:
As before, we can check if whether it's Amazon Linux 2023 in the when block directly.

2023-04-10 11:39 UTC, alessfg commented on tasks/main.yml
> +  when: (nginx_enable | bool and nginx_install_from == 'nginx_repository') or nginx_amplify_enable | bool
Can we split this back into two lines? It was split on purpose to help with clarity.

2023-04-10 11:39 UTC, alessfg commented on tasks/config/setup-logrotate.yml
> +    enablerepo: nginx-mainline-repo
Do we need to set enablerepo/disablerepo even if we are not installing NGINX in this task?

2023-04-10 11:39 UTC, alessfg commented on tasks/modules/install-modules.yml
> +  vars:
See comment on logrotate tasks. Let's do the comparison for this directly in the `when` conditional block.

2023-04-10 11:39 UTC, alessfg commented on tasks/modules/install-modules.yml
> +      and distribution != 'Amazon LInux 2023'"
While at it, if we are going to separate this conditional into two lines, let's do it at the `or`, not like it is done right now.

2023-04-10 11:39 UTC, alessfg commented on tasks/modules/install-modules.yml
> +  vars:
See all my previous comments re vars block vs conditionals.

2023-04-10 11:39 UTC, alessfg commented on tasks/modules/install-modules.yml
> +    enablerepo: nginx-mainline-repo
Do we need to enablerepo/disablerepo here?

2023-04-10 11:39 UTC, alessfg commented on tasks/modules/install-modules.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/modules/install-modules.yml
> +          }}
Combine into single line.

2023-04-10 11:39 UTC, alessfg commented on tasks/modules/install-modules.yml
> +          }}.noarch.rpm
Combine into single line.

2023-04-10 11:39 UTC, alessfg commented on tasks/modules/install-modules.yml
> +      == 'Alpine' and nginx_type != 'plus') | ternary('@nginx', '') }}{{ item['version'] | default('') }}
Combine to previous format.

2023-04-10 11:39 UTC, alessfg commented on tasks/modules/install-modules.yml
> +      '=='))
Revert to previous format :)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-distribution.yml
> +          }}
Revert to previous format :)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-distribution.yml
> +          }}.noarch.rpm
Revert to previous format :)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-distribution.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-distribution.yml
> +    - distribution == 'Amazon Linux 2023'
This task involves installing NGINX from the Amazon repo. I am pretty sure that's not what this block does? I am also not entirely sure if we even need an Amazon Linux 2023 specific task or whether NGINX is available in the core  Amazon Linux 2023 packages? (Judging by the fact you had to disable the amazonlinux repo I assume it is?)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-redhat.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-redhat.yml
> +      \ }}"
Revert :)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-redhat.yml
> +- name: (Amazon Linux 2023) {{ (nginx_setup == 'uninstall') | ternary('Remove', 'Configure') }} NGINX stable repository
Check what's being done behind the scenes in the vars file. I'd like to keep everything contained within the task that already exists.

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-redhat.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-source.yml
> +      vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-source.yml
> +          vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-source.yml
> +          \ 'https://ftp.exim.org/pub/pcre/pcre-' ~ pcre_version ~ '.tar.gz') }}"
Revert :)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-source.yml
> +      vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/opensource/install-source.yml
> -
Not entirely sure why Ansible lint removed this line but let's put it back :)

2023-04-10 11:39 UTC, alessfg commented on tasks/plus/install-redhat.yml
> +    'Configure') }} NGINX Plus repository
Revert back to a single line :)

2023-04-10 11:39 UTC, alessfg commented on tasks/plus/install-redhat.yml
> +      \ }}"
Revert :)

2023-04-10 11:39 UTC, alessfg commented on tasks/plus/install-redhat.yml
> +    - nginx_manage_repo | bool
Revert :)

2023-04-10 11:39 UTC, alessfg commented on tasks/plus/install-redhat.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/plus/install-redhat.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/plus/install-redhat.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/plus/install-redhat.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/prerequisites/install-dependencies.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/prerequisites/install-dependencies.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/prerequisites/prerequisites.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/prerequisites/setup-selinux.yml
> +  vars:
Remove :)

2023-04-10 11:39 UTC, alessfg commented on tasks/validate/validate.yml
Revert all changes here to the previous format

2023-04-10 11:39 UTC, alessfg commented on vars/main.yml
Revert all formatting changes here

2023-07-03 06:47 UTC, jskelly84 approved these changes

2023-07-03 18:38 UTC, alessfg commented
Thanks for the updates!

1. Looks like some Molecule scenarios are still missing 😄 (e.g. there is no AL2023 platform in the `default` scenario). If you could comment out/remove the `platform` parameter (e.g. https://github.com/nginxinc/ansible-role-nginx/pull/597/files#diff-f653be9e6e7813c18a248edeb270c6a8034e1ed3b0ea3e49e6e6a9192f740201R65) for the time being, that'd be great. The pipeline has been running into some emulation related issues.
2. The linter is failing -- not entirely sure why but there might be some issues with the YAML code you've written.

2023-07-04 19:28 UTC, sbezugliy commented
Molecule is new for me, but I know what to do with it. So, trying...
Yes, I'll check one more time syntax and next fix. Looks like typo with quotes.

2024-04-16 16:26 UTC, alessfg commented
Closing this PR in favor of #706.

2024-04-16 16:26 UTC, closed without merging